name: kbkit
channels:
  - conda-forge
dependencies:
  - python >=3.12
  - pip
  - hatchling
  - numpy >=2.3.2,<3
  - natsort >=8.4.0,<9
  - scipy >=1.16.1,<2
  - pandas >=2.3.1,<3
  - matplotlib >=3.10.5,<4
  - seaborn >=0.13.2,<0.14
  - gromacs >=2023.4.0
  - pathlib >=1.0.1,<2
  - mpltern >=1.0.4,<2
  - plotly >=6.3.0,<7
  - click >=8.2.1,<9
  - pint <0.25
  - uncertainties >=3.2.3,<4
  - babel >=2.17.0,<3
  - ipykernel >=6.30.1,<7
  - rdkit >=2025.3.5,<2026
  - sympy >=1.14.0,<2
  - mypy
  - mdanalysis
  - pytest
  - pytest-cov
